# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test_Project.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formulario(object):
    def setupUi(self, Formulario):
        Formulario.setObjectName("Formulario")
        Formulario.resize(675, 417)
        Formulario.setStyleSheet("#Formulario{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"#contenedor_principal{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"#etiqueta_salarios{\n"
"height:30px;\n"
"max-height:30px;\n"
"font-size:24px;\n"
"font-weight:bold;\n"
"font-family:\'Arial\';\n"
"background-color: rgb(255, 255, 255);\n"
"padding-left:10px;\n"
"}\n"
"#btn_ejecutar{\n"
"font-size:16px;\n"
"font-weight:bold;\n"
"font-family:\'Arial\';\n"
"background-color: rgb(93, 223, 72);\n"
"border:none;\n"
"border-radius: 5px;\n"
"min-height:30px;\n"
"padding-left: 5px;\n"
"padding-right:5px;\n"
"color:rgb(241, 241, 241);\n"
"margin-bottom:10px;\n"
"}\n"
"#btn_ejecutar:hover{\n"
"background-color: rgb(99, 206, 97);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Formulario)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.contenedor_principal = QtWidgets.QFrame(Formulario)
        self.contenedor_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_principal.setObjectName("contenedor_principal")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.contenedor_principal)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_ejecutar = QtWidgets.QPushButton(self.contenedor_principal)
        self.btn_ejecutar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ejecutar.setObjectName("btn_ejecutar")
        self.gridLayout_2.addWidget(self.btn_ejecutar, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.contenedor_grafico = QtWidgets.QFrame(self.contenedor_principal)
        self.contenedor_grafico.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_grafico.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_grafico.setObjectName("contenedor_grafico")
        self.gridLayout_2.addWidget(self.contenedor_grafico, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.contenedor_principal, 2, 0, 1, 1)
        self.etiqueta_salarios = QtWidgets.QLabel(Formulario)
        self.etiqueta_salarios.setObjectName("etiqueta_salarios")
        self.gridLayout.addWidget(self.etiqueta_salarios, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(Formulario)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)

        self.retranslateUi(Formulario)
        QtCore.QMetaObject.connectSlotsByName(Formulario)

    def retranslateUi(self, Formulario):
        _translate = QtCore.QCoreApplication.translate
        Formulario.setWindowTitle(_translate("Formulario", "Form"))
        self.btn_ejecutar.setText(_translate("Formulario", "Ejecutar"))
        self.etiqueta_salarios.setText(_translate("Formulario", "Salarios"))
